// Generated by RPG Maker MV.
// Do not edit this file directly.
var $plugins =
[
  {
    "name": "SamplePlugin",
    "status": true,
    "description": "A sample plugin",
    "parameters": {
      "Enabled": "true",
      "MaxCount": "10"
    }
  }
];