// Generated by RPG Maker MV.
// Do not edit this file directly.
var $plugins =
[
  {
    "name": "MZPlugin",
    "status": true,
    "description": "An MZ plugin",
    "parameters": {
      "Key": "Value"
    }
  }

];