// Generated by RPG Maker MV.
// Do not edit this file directly.
var $plugins =
[
  {
    "name": "BadPlugin",
    "status": true,
    "description": "bad",
    "parameters": {
      "Count": 10
    }
  }
];
