import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const SAMPLE_DIR = 'test/fixtures/sample-project';
const BROKEN_DIR = 'test/fixtures/broken-project';

function ensureDir(dir: string) {
  if (existsSync(dir)) rmSync(dir, { recursive: true });
  mkdirSync(dir, { recursive: true });
}

function writeJson(filePath: string, data: unknown) {
  writeFileSync(filePath, JSON.stringify(data), 'utf-8');
}

function writePluginsJs(filePath: string, plugins: unknown[]) {
  const header = '// Generated by RPG Maker MV.\n// Do not edit this file directly.\nvar $plugins =\n';
  const json = JSON.stringify(plugins, null, 2);
  const body = json === "[]" ? "[]" : `${json.slice(0, -2)}\n];`;
  writeFileSync(filePath, `${header}${body}\n`, 'utf-8');
}

function nullIndexed<T extends { id: number }>(items: T[]): (T | null)[] {
  const arr: (T | null)[] = [null];
  for (const item of items) arr[item.id] = item;
  return arr;
}

const AUDIO = { name: '', volume: 90, pitch: 100, pan: 0 };
const PARAMS = [0, 0, 0, 0, 0, 0, 0, 0];

function system() {
  return {
    gameTitle: 'Sample Game', versionId: 1, currencyUnit: 'G',
    elements: ['', 'Fire', 'Ice', 'Lightning', 'Heal'],
    skillTypes: ['', 'Magic', 'Special'],
    weaponTypes: ['', 'Sword', 'Staff'],
    armorTypes: ['', 'Shield', 'Hat'],
    equipTypes: ['', 'Weapon', 'Shield', 'Head'],
    switches: ['', 'Switch1', 'Switch2'],
    variables: ['', 'Var1', 'Var2'],
    terms: { basic: Array(10).fill(''), commands: Array(10).fill(''), params: Array(8).fill(''), messages: {} },
    startMapId: 1, startX: 0, startY: 0, partyMembers: [1],
    title1Name: '', title2Name: '',
    optExtraExp: false, optExtraGold: false, optFloorDeath: false, optSideView: false,
    optSlipDeath: false, optKeyItemsNumber: false, optDisplayTp: true,
    optTransparent: false, optAutosave: true,
    battleback1Name: '', battleback2Name: '', battlerName: '',
    battleBgm: { ...AUDIO }, defeatMe: { ...AUDIO }, victoryMe: { ...AUDIO }, gameoverMe: { ...AUDIO },
    sounds: Array(24).fill(null).map(() => ({ ...AUDIO })),
    testBattlers: [], battleSystem: 0, battlerHue: 0,
    editMapId: 1,
  };
}

function items() {
  return nullIndexed([
    { id: 1, name: 'Potion', iconIndex: 0, description: 'Restores 100 HP', itypeId: 1, scope: 7, occasion: 0, speed: 0, successRate: 100, repeats: 1, tpGain: 0, hitType: 0, animationId: 0, price: 100, consumable: true, damage: { type: 3, elementId: 0, formula: '100', variance: 10, critical: false }, effects: [], note: '<type:healing>', meta: { type: 'healing' } },
    { id: 2, name: 'Ether', iconIndex: 0, description: 'Restores 50 MP', itypeId: 1, scope: 7, occasion: 0, speed: 0, successRate: 100, repeats: 1, tpGain: 0, hitType: 0, animationId: 0, price: 200, consumable: true, damage: { type: 4, elementId: 0, formula: '50', variance: 10, critical: false }, effects: [], note: '', meta: {} },
    { id: 3, name: 'Key Item', iconIndex: 0, description: 'A mysterious key', itypeId: 2, scope: 0, occasion: 2, speed: 0, successRate: 100, repeats: 1, tpGain: 0, hitType: 0, animationId: 0, price: 0, consumable: false, damage: { type: 0, elementId: 0, formula: '0', variance: 0, critical: false }, effects: [], note: '', meta: {} },
  ]);
}

function skills() {
  return nullIndexed([
    { id: 1, name: 'Attack', iconIndex: 0, description: '', stypeId: 1, mpCost: 0, tpCost: 0, scope: 1, occasion: 1, speed: 0, successRate: 100, repeats: 1, tpGain: 10, hitType: 1, animationId: 0, message1: ' attacks!', message2: '', requiredWtypeId1: 0, requiredWtypeId2: 0, damage: { type: 1, elementId: 0, formula: 'a.atk * 4 - b.def * 2', variance: 20, critical: true }, effects: [], note: '', meta: {} },
    { id: 2, name: 'Fire', iconIndex: 0, description: 'Fire damage', stypeId: 1, mpCost: 10, tpCost: 0, scope: 1, occasion: 1, speed: 0, successRate: 100, repeats: 1, tpGain: 0, hitType: 1, animationId: 0, message1: ' casts Fire!', message2: '', requiredWtypeId1: 0, requiredWtypeId2: 0, damage: { type: 1, elementId: 1, formula: 'a.mat * 4 - b.mdf * 2', variance: 20, critical: false }, effects: [], note: '<element:fire>', meta: { element: 'fire' } },
    { id: 3, name: 'Heal', iconIndex: 0, description: 'Restores HP', stypeId: 1, mpCost: 8, tpCost: 0, scope: 7, occasion: 1, speed: 0, successRate: 100, repeats: 1, tpGain: 0, hitType: 0, animationId: 0, message1: ' casts Heal!', message2: '', requiredWtypeId1: 0, requiredWtypeId2: 0, damage: { type: 3, elementId: 4, formula: 'a.mat * 3', variance: 10, critical: false }, effects: [], note: '', meta: {} },
  ]);
}

function weapons() {
  return nullIndexed([
    { id: 1, name: 'Iron Sword', iconIndex: 0, description: 'A basic sword', wtypeId: 1, price: 500, etypeId: 1, params: [0, 0, 10, 0, 0, 0, 0, 0], traits: [], note: '' },
    { id: 2, name: 'Oak Staff', iconIndex: 0, description: 'A wooden staff', wtypeId: 2, price: 300, etypeId: 1, params: [0, 0, 0, 0, 8, 0, 0, 0], traits: [], note: '' },
  ]);
}

function armors() {
  return nullIndexed([
    { id: 1, name: 'Leather Shield', iconIndex: 0, description: 'A leather shield', atypeId: 1, etypeId: 2, price: 200, params: [0, 0, 0, 5, 0, 0, 0, 0], traits: [], note: '' },
    { id: 2, name: 'Leather Hat', iconIndex: 0, description: 'A simple hat', atypeId: 2, etypeId: 3, price: 150, params: [0, 0, 0, 2, 0, 0, 0, 0], traits: [], note: '' },
  ]);
}

function states() {
  return nullIndexed([
    { id: 1, name: 'Knockout', iconIndex: 0, restriction: 4, priority: 100, motion: 0, overlay: 0, removeAtBattleEnd: false, removeByRestriction: false, autoRemovalTiming: 0, minTurns: 1, maxTurns: 1, removeByDamage: 0, chanceByDamage: 0, removeByWalking: 0, stepsToRemove: 100, message1: ' has fallen!', message2: '', message3: '', message4: '', traits: [], note: '' },
    { id: 2, name: 'Poison', iconIndex: 0, restriction: 0, priority: 50, motion: 0, overlay: 1, removeAtBattleEnd: true, removeByRestriction: true, autoRemovalTiming: 1, minTurns: 3, maxTurns: 5, removeByDamage: 30, chanceByDamage: 100, removeByWalking: 0, stepsToRemove: 100, message1: ' is poisoned!', message2: '', message3: '', message4: '', traits: [], note: '' },
  ]);
}

function enemies() {
  return nullIndexed([
    { id: 1, name: 'Slime', battlerName: 'slime', battlerHue: 0, params: [100, 0, 10, 5, 5, 5, 8, 5], exp: 10, gold: 5, dropItems: [{ kind: 1, dataId: 1, denominator: 2 }], actions: [{ conditionType: 0, conditionParam1: 0, conditionParam2: 0, rating: 5, skillId: 1 }], traits: [], note: '' },
    { id: 2, name: 'Bat', battlerName: 'bat', battlerHue: 0, params: [60, 0, 8, 3, 3, 3, 12, 3], exp: 5, gold: 3, dropItems: [], actions: [{ conditionType: 0, conditionParam1: 0, conditionParam2: 0, rating: 5, skillId: 1 }], traits: [], note: '' },
  ]);
}

function actors() {
  return nullIndexed([
    { id: 1, name: 'Hero', nickname: 'The Hero', classId: 1, initialLevel: 1, maxLevel: 99, profile: 'A brave hero.', faceName: '', faceIndex: 0, characterName: '', characterIndex: 0, battlerName: '', equips: [1, 1, 2, 0, 0], traits: [], note: '' },
    { id: 2, name: 'Mage', nickname: 'The Mage', classId: 2, initialLevel: 1, maxLevel: 99, profile: 'A wise mage.', faceName: '', faceIndex: 0, characterName: '', characterIndex: 0, battlerName: '', equips: [2, 0, 0, 0, 0], traits: [], note: '' },
  ]);
}

function classes() {
  return nullIndexed([
    { id: 1, name: 'Fighter', expParams: [30, 20, 20, 10], params: PARAMS.map(() => Array(99).fill(10)), learnings: [{ level: 1, skillId: 1, note: '' }, { level: 3, skillId: 2, note: '' }], traits: [], note: '' },
    { id: 2, name: 'Mage', expParams: [30, 20, 20, 10], params: PARAMS.map(() => Array(99).fill(10)), learnings: [{ level: 1, skillId: 1, note: '' }, { level: 2, skillId: 3, note: '' }], traits: [], note: '' },
  ]);
}

function troops() {
  return nullIndexed([
    { id: 1, name: 'Slime Group', members: [{ enemyId: 1, x: 0, y: 0, hidden: false }, { enemyId: 1, x: 1, y: 0, hidden: false }], pages: [{ conditions: { actorHp: 50, actorId: 1, actorValid: false, enemyHp: 50, enemyIndex: 0, enemyValid: false, switchId: 1, switchValid: false, turnA: 0, turnB: 0, turnEnding: false, turnValid: false }, list: [{ code: 0, indent: 0, parameters: [] }], span: 0 }] },
  ]);
}

function commonEvents() {
  return nullIndexed([
    { id: 1, name: 'Opening', trigger: 0, switchId: 1, list: [{ code: 0, indent: 0, parameters: [] }] },
  ]);
}

function mapInfos() {
  return nullIndexed([
    { id: 1, name: 'Start Map', parentId: 0, order: 1, expanded: true, scrollX: 0, scrollY: 0 },
  ]);
}

function map001() {
  return {
    autoplayBgm: false, autoplayBgs: false, battleback1Name: '', battleback2Name: '',
    bgm: { ...AUDIO }, bgs: { ...AUDIO }, disableDashing: false,
    displayName: '', encounterList: [], encounterStep: 30,
    events: nullIndexed([
      { id: 1, name: 'NPC', x: 5, y: 5, pages: [{ conditions: { actorId: 1, actorValid: false, itemId: 1, itemValid: false, selfSwitchCh: 'A', selfSwitchValid: false, switch1Id: 1, switch1Valid: false, switch2Id: 1, switch2Valid: false, variableId: 1, variableValid: false, variableValue: 0 }, directionFix: false, image: { tileId: 0, characterName: '', characterIndex: 0, direction: 2, pattern: 0 }, list: [{ code: 101, indent: 0, parameters: ['', 0, 0, 2] }, { code: 401, indent: 0, parameters: ['Hello, adventurer!'] }, { code: 0, indent: 0, parameters: [] }], moveFrequency: 3, moveRoute: { list: [{ code: 0, indent: 0, parameters: [] }], repeat: true, skippable: false, wait: false }, moveSpeed: 3, moveType: 0, priorityType: 0, stepAnime: false, through: false, trigger: 0, walkAnime: true }], note: '' },
    ]),
    note: '', parallaxLoopX: false, parallaxLoopY: false,
    parallaxName: '', parallaxShow: false, parallaxSx: 0, parallaxSy: 0,
    scrollType: 0, specifyBattleback: false,
    tilesetId: 1, width: 20, height: 15,
    data: new Array(20 * 15 * 6).fill(0),
  };
}

function generateSample() {
  ensureDir(SAMPLE_DIR);
  const dataDir = join(SAMPLE_DIR, 'data');
  const pluginsDir = join(SAMPLE_DIR, 'js', 'plugins');
  mkdirSync(dataDir, { recursive: true });
  mkdirSync(pluginsDir, { recursive: true });

  writeFileSync(join(SAMPLE_DIR, 'Game.rpgproject'), '', 'utf-8');
  writeJson(join(dataDir, 'System.json'), system());
  writeJson(join(dataDir, 'Items.json'), items());
  writeJson(join(dataDir, 'Skills.json'), skills());
  writeJson(join(dataDir, 'Weapons.json'), weapons());
  writeJson(join(dataDir, 'Armors.json'), armors());
  writeJson(join(dataDir, 'States.json'), states());
  writeJson(join(dataDir, 'Enemies.json'), enemies());
  writeJson(join(dataDir, 'Actors.json'), actors());
  writeJson(join(dataDir, 'Classes.json'), classes());
  writeJson(join(dataDir, 'Troops.json'), troops());
  writeJson(join(dataDir, 'CommonEvents.json'), commonEvents());
  writeJson(join(dataDir, 'MapInfos.json'), mapInfos());
  writeJson(join(dataDir, 'Map001.json'), map001());
  writeJson(join(dataDir, 'Animations.json'), [null]);
  writeJson(join(dataDir, 'Tilesets.json'), [null]);
  writePluginsJs(join(SAMPLE_DIR, 'js', 'plugins.js'), [
    { name: 'SamplePlugin', status: true, description: 'A sample plugin', parameters: { Enabled: 'true', MaxCount: '10' } },
  ]);
  writeFileSync(join(pluginsDir, 'SamplePlugin.js'), '/* Sample Plugin */', 'utf-8');
}

function generateBroken() {
  ensureDir(BROKEN_DIR);
  const dataDir = join(BROKEN_DIR, 'data');
  const pluginsDir = join(BROKEN_DIR, 'js', 'plugins');
  mkdirSync(dataDir, { recursive: true });
  mkdirSync(pluginsDir, { recursive: true });

  writeFileSync(join(BROKEN_DIR, 'Game.rpgproject'), '', 'utf-8');

  const sys = system();
  writeJson(join(dataDir, 'System.json'), sys);

  // Dangling animationId (references animation 99 which doesn't exist)
  const brokenSkills = nullIndexed([
    { id: 1, name: 'Bad Skill', iconIndex: 0, description: '', stypeId: 1, mpCost: 0, tpCost: 0, scope: 1, occasion: 1, speed: 0, successRate: 100, repeats: 1, tpGain: 10, hitType: 1, animationId: 99, message1: '!', message2: '', requiredWtypeId1: 0, requiredWtypeId2: 0, damage: { type: 1, elementId: 0, formula: 'a.atk', variance: 0, critical: false }, effects: [], note: '<broken', meta: {} },
  ]);
  writeJson(join(dataDir, 'Skills.json'), brokenSkills);

  // Duplicate id (two items with id 1)
  const brokenItems: unknown[] = [null,
    { id: 1, name: 'Item A', iconIndex: 0, description: '', itypeId: 1, scope: 0, occasion: 0, speed: 0, successRate: 100, repeats: 1, tpGain: 0, hitType: 0, animationId: 0, price: 0, consumable: true, damage: { type: 0, elementId: 0, formula: '0', variance: 0, critical: false }, effects: [], note: '', meta: {} },
    { id: 1, name: 'Item B', iconIndex: 0, description: '', itypeId: 1, scope: 0, occasion: 0, speed: 0, successRate: 100, repeats: 1, tpGain: 0, hitType: 0, animationId: 0, price: 0, consumable: true, damage: { type: 0, elementId: 0, formula: '0', variance: 0, critical: false }, effects: [], note: '', meta: {} },
  ];
  writeJson(join(dataDir, 'Items.json'), brokenItems);

  // skillId past array bounds
  const brokenClasses = nullIndexed([
    { id: 1, name: 'Bad Class', expParams: [30, 20, 20, 10], params: PARAMS.map(() => Array(99).fill(10)), learnings: [{ level: 1, skillId: 50, note: '' }], traits: [], note: '' },
  ]);
  writeJson(join(dataDir, 'Classes.json'), brokenClasses);

  // Non-string plugin param
  writePluginsJs(join(BROKEN_DIR, 'js', 'plugins.js'), [
    { name: 'BadPlugin', status: true, description: 'bad', parameters: { Count: 10 } },
  ]);

  // Minimal valid files for the rest
  writeJson(join(dataDir, 'Weapons.json'), [null]);
  writeJson(join(dataDir, 'Armors.json'), [null]);
  writeJson(join(dataDir, 'States.json'), [null]);
  writeJson(join(dataDir, 'Enemies.json'), [null]);
  writeJson(join(dataDir, 'Actors.json'), [null]);
  writeJson(join(dataDir, 'Troops.json'), [null]);
  writeJson(join(dataDir, 'CommonEvents.json'), [null]);
  writeJson(join(dataDir, 'MapInfos.json'), [null]);
  writeJson(join(dataDir, 'Animations.json'), [null]);
  writeJson(join(dataDir, 'Tilesets.json'), [null]);
}

// MZ uses Game.mzproject instead of Game.rpgproject
// and has Effekseer-based animations with effectName field
function mzAnimations() {
  return nullIndexed([
    { id: 1, name: 'Fire', animation1Name: '', animation1Hue: 0, animation2Name: '', animation2Hue: 0, position: 1, effectName: 'Fire.efkefc', effekseerFlags: 0, frames: [], timings: [], note: '' },
  ]);
}

function generateMzSample() {
  const MZ_DIR = 'test/fixtures/mz-sample-project';
  ensureDir(MZ_DIR);
  const dataDir = join(MZ_DIR, 'data');
  const pluginsDir = join(MZ_DIR, 'js', 'plugins');
  mkdirSync(dataDir, { recursive: true });
  mkdirSync(pluginsDir, { recursive: true });

  writeFileSync(join(MZ_DIR, 'Game.mzproject'), '', 'utf-8');
  writeJson(join(dataDir, 'System.json'), system());
  writeJson(join(dataDir, 'Items.json'), items());
  writeJson(join(dataDir, 'Skills.json'), skills());
  writeJson(join(dataDir, 'Weapons.json'), weapons());
  writeJson(join(dataDir, 'Armors.json'), armors());
  writeJson(join(dataDir, 'States.json'), states());
  writeJson(join(dataDir, 'Enemies.json'), enemies());
  writeJson(join(dataDir, 'Actors.json'), actors());
  writeJson(join(dataDir, 'Classes.json'), classes());
  writeJson(join(dataDir, 'Troops.json'), troops());
  writeJson(join(dataDir, 'CommonEvents.json'), commonEvents());
  writeJson(join(dataDir, 'MapInfos.json'), mapInfos());
  writeJson(join(dataDir, 'Map001.json'), map001());
  writeJson(join(dataDir, 'Animations.json'), mzAnimations());
  writeJson(join(dataDir, 'Tilesets.json'), [null]);
  writePluginsJs(join(MZ_DIR, 'js', 'plugins.js'), [
    { name: 'MZPlugin', status: true, description: 'An MZ plugin', parameters: { Key: 'Value' } },
  ]);
  writeFileSync(join(pluginsDir, 'MZPlugin.js'), '// MZ Plugin', 'utf-8');
}

generateSample();
generateBroken();
generateMzSample();

