import { readFileSync } from "node:fs";
import { join } from "node:path";
import { IoError } from "../errors.js";

export interface PluginEntry {
  name: string;
  status: boolean;
  description: string;
  parameters: Record<string, string>;
}

const HEADER =
  "// Generated by RPG Maker MV.\n// Do not edit this file directly.\nvar $plugins =\n";

export function parsePluginsJs(content: string): PluginEntry[] {
  const bracketStart = content.indexOf("[");
  if (bracketStart === -1) {
    throw new IoError("plugins.js", "No array literal found");
  }

  let depth = 0;
  let bracketEnd = -1;
  for (let i = bracketStart; i < content.length; i++) {
    if (content[i] === "[") depth++;
    else if (content[i] === "]") {
      depth--;
      if (depth === 0) {
        bracketEnd = i;
        break;
      }
    }
  }

  if (bracketEnd === -1) {
    throw new IoError("plugins.js", "Unmatched bracket");
  }

  const arrayStr = content.slice(bracketStart, bracketEnd + 1);
  return JSON.parse(arrayStr) as PluginEntry[];
}

export function serializePluginsJs(plugins: PluginEntry[]): string {
  const json = JSON.stringify(plugins, null, 2);
  return `${HEADER}${json.slice(0, -2)}\n];`;
}

export function readPluginsJs(projectDir: string): PluginEntry[] {
  const filePath = join(projectDir, "js", "plugins.js");
  try {
    const content = readFileSync(filePath, "utf-8");
    return parsePluginsJs(content);
  } catch (err) {
    if (err instanceof IoError) throw err;
    throw new IoError(filePath, err);
  }
}
