import { readFileSync } from "node:fs";
import { z } from "zod";
import { IoError } from "../errors.js";
import { PluginEntrySchema } from "../schema/entities.js";
import { PluginName } from "../schema/safety.js";
import { resolveProjectPath } from "./paths.js";

export interface PluginEntry {
  name: string;
  status: boolean;
  description: string;
  parameters: Record<string, unknown>;
}

const HEADER =
  "// Generated by RPG Maker MV.\n// Do not edit this file directly.\nvar $plugins =\n";

export function parsePluginsJs(content: string): PluginEntry[] {
  const assignment =
    /^(?:\s|\/\/[^\n]*(?:\n|$)|\/\*[\s\S]*?\*\/)*(?:var|let|const)\s+\$plugins\s*=\s*/.exec(
      content,
    );
  const bracketStart = assignment ? assignment[0].length : -1;
  if (bracketStart === -1) {
    throw new IoError("plugins.js", "No array literal found");
  }

  let depth = 0;
  let quoted = false;
  let escaped = false;
  let bracketEnd = -1;
  for (let i = bracketStart; i < content.length; i++) {
    if (quoted) {
      if (escaped) escaped = false;
      else if (content[i] === "\\") escaped = true;
      else if (content[i] === '"') quoted = false;
      continue;
    }
    if (content[i] === '"') {
      quoted = true;
      continue;
    }
    if (content[i] === "[") depth++;
    else if (content[i] === "]") {
      depth--;
      if (depth === 0) {
        bracketEnd = i;
        break;
      }
    }
  }

  if (bracketEnd === -1) {
    throw new IoError("plugins.js", "Unmatched bracket");
  }

  const arrayStr = content.slice(bracketStart, bracketEnd + 1);
  try {
    return PluginEntrySchema.extend({ name: PluginName, parameters: z.record(z.unknown()) })
      .passthrough()
      .array()
      .parse(JSON.parse(arrayStr));
  } catch (error) {
    throw new IoError("plugins.js", error);
  }
}

export function serializePluginsJs(plugins: PluginEntry[]): string {
  return `${HEADER}${JSON.stringify(plugins, null, 2)};\n`;
}

export function readPluginsJs(projectDir: string): PluginEntry[] {
  const filePath = resolveProjectPath(projectDir, "js/plugins.js");
  try {
    const content = readFileSync(filePath, "utf-8");
    return parsePluginsJs(content);
  } catch (err) {
    if (err instanceof IoError) throw err;
    throw new IoError(filePath, err);
  }
}
