import { describe, it, expect } from "vitest";
import { parsePluginsJs, serializePluginsJs } from "../../src/io/pluginsJs.js";

describe("pluginsJs", () => {
  it("parses valid plugins.js content", () => {
    const content = `// Generated by RPG Maker MV.\n// Do not edit this file directly.\nvar $plugins =\n[{"name":"Test","status":true,"description":"desc","parameters":{"Key":"Value"}}]\n;`;
    const result = parsePluginsJs(content);
    expect(result).toHaveLength(1);
    expect(result[0].name).toBe("Test");
    expect(result[0].status).toBe(true);
    expect(result[0].parameters.Key).toBe("Value");
  });

  it("parses empty array", () => {
    const content = `// header\nvar $plugins =\n[]\n;`;
    const result = parsePluginsJs(content);
    expect(result).toHaveLength(0);
  });

  it("round-trips through serialize/parse", () => {
    const plugins = [
      { name: "A", status: true, description: "d", parameters: { K: "V" } },
      { name: "B", status: false, description: "d2", parameters: {} },
    ];
    const serialized = serializePluginsJs(plugins);
    const parsed = parsePluginsJs(serialized);
    expect(parsed).toEqual(plugins);
  });

  it("preserves header format", () => {
    const serialized = serializePluginsJs([]);
    expect(serialized).toContain("// Generated by RPG Maker MV.");
    expect(serialized).toContain("var $plugins =");
  });

  it("throws on missing bracket", () => {
    expect(() => parsePluginsJs("no bracket here")).toThrow();
  });
});
